version: '3.4'
services:
  page_disk-service:
    build:
      context: ./page_disk-service
    network_mode: "host" 
    ports:
      - "9999:9999"
    depends_on:
      - mongodb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_HOST=mongodb
      - DEBUG=1
      - DATABASE_HOST=127.0.0.1
      - DATABASE_PORT=27017
      - GOPATH=/root/go
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/go/bin:/root/go/bin

  mongodb:
    build: ./mongo-database
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
      - db-config:/data/configdb

volumes:
  db-data:
  db-config:



